include: package:very_good_analysis/analysis_options.3.0.0.yaml


analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/*.mocks.dart"
  
  language:
    strict-raw-types: true
    strict-casts: true
    strict-inference: true
  
  errors:
    missing_required_param: error
    missing_return: error
    avoid_unused_constructor_parameters: error
    # prefer_relative_imports: error
  
  plugins:
    - custom_lint
    - dart_code_metrics

linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - avoid_empty_else
    - avoid_print
    - camel_case_types
    - constant_identifier_names
    - file_names
    - flutter_style_todos
    - library_names
    - lines_longer_than_80_chars
    - no_duplicate_case_values
    - no_logic_in_create_state
    - one_member_abstracts
    - package_api_docs
    - package_prefixed_library_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    # - prefer_relative_imports
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - test_types_in_equals
    - type_init_formals
    - unnecessary_const
    - unnecessary_new
    - unnecessary_statements
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - valid_regexps

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 5
    maximum-nesting-level: 5
  
  metrics-exclude:
    - test/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  rules:
    - no-magic-number:
        allowed: [0, 1, 2, 10, 100, 1000, -1]
    - member-ordering:
        order:
          - constructors
          - factory-constructors
          - static-methods
          - instance-variables
          - override-instance-variables
          - instance-methods
          - override-instance-methods
    - prefer-trailing-comma
    - no-boolean-literal-compare
    - prefer-conditional-expressions