name: enterprise_app

packages:
  - "."

scripts:
  analyze:
    run: fvm flutter analyze --fatal-infos
    description: "Run Flutter analysis"
  
  test:
    run: fvm flutter test --coverage --test-randomize-ordering-seed=random
    description: "Run tests with coverage"
  
  format:
    run: fvm flutter format --set-exit-if-changed .
    description: "Format code"
  
  build_runner:
    run: fvm flutter packages pub run build_runner build --delete-conflicting-outputs
    description: "Run code generation"
  
  build_runner_watch:
    run: fvm flutter packages pub run build_runner watch --delete-conflicting-outputs
    description: "Watch for changes and generate code"
  
  clean:
    run: fvm flutter clean && rm -rf pubspec.lock && fvm flutter pub get
    description: "Clean and refresh dependencies"
  
  icons:
    run: fvm flutter pub run flutter_launcher_icons
    description: "Generate app icons"
  
  localization:
    run: fvm flutter gen-l10n
    description: "Generate localization files"

  run_dev:
    run: ./scripts/run/run_app.sh -f dev
    description: "Run the app in dev flavor"
  
  run_staging:
    run: ./scripts/run/run_app.sh -f staging
    description: "Run the app in staging flavor"
  
  run_prod:
    run: ./scripts/run/run_app.sh -f prod
    description: "Run the app in prod flavor"
  
  run_list_devices:
    run: ./scripts/run/run_app.sh -l
    description: "List available devices"
  