import 'package:flutter_enterprise_boilerplate/app/app_bloc_observer.dart';
import 'package:flutter_enterprise_boilerplate/app/app_config.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

// Module exports
export 'modules/network_module.dart';
export 'modules/storage_module.dart';

/*
 Role: who exists and how they are wired, Build the object graph: which classes are singletons,
 what each constructor needs, how interfaces map to implementations,
 values from @module methods.
*/

///*** IMPORTANT
/// At codegen time, "injectable_config_builder" scans the dependency graph and 
/// asks: "Can I find a registration for every constructor parameter?", 
/// It does not run your app or execute configureInjection().
/// */

/// GetIt instance
final GetIt getIt = GetIt.instance;

@InjectableInit(
  // *** This is the name of the function that will be generated by Injectable.
  // It will be used to initialize the GetIt instance.
  initializerName: r'$initGetIt',
  preferRelativeImports: true,
  asExtension: false,
  // *** This is to ignore the AppConfig type because it is not a registered type.
  ignoreUnregisteredTypes: [AppConfig],

)
Future<void> configureInjection(AppConfig appConfig) async {

  // 1. MANUALLY register AppConfig as a singleton
  // This happens BEFORE code generation runs
  getIt.registerSingleton<AppConfig>(appConfig);
  
  // 2. Run code generation to register all @injectable classes
  // These classes can now depend on AppConfig because it's already registered
  await $initGetIt(
    getIt,
    //environment: _getEnvironment(appConfig.flavor),
  );

   // 3. Verify registration (optional)
  assert(getIt.isRegistered<AppConfig>());
}

// String _getEnvironment(Flavor flavor) {
//   switch (flavor) {
//     case Flavor.development:
//       return Environment.dev;
//     case Flavor.staging:
//       return Environment.;
//     case Flavor.production:
//       return Environment.prod;
//   }
// }

