import 'package:flutter_enterprise_boilerplate/app/app_bloc_observer.dart';
import 'package:flutter_enterprise_boilerplate/app/app_config.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

// Module exports
export 'modules/network_module.dart';
export 'modules/storage_module.dart';

/*
 Role: who exists and how they are wired, Build the object graph: which classes are singletons,
 what each constructor needs, how interfaces map to implementations,
 values from @module methods.
*/

///*** IMPORTANT
/// At codegen time, "injectable_config_builder" scans the dependency graph and 
/// asks: "Can I find a registration for every constructor parameter?", 
/// It does not run your app or execute configureInjection().
/// */

/// GetIt instance
final GetIt getIt = GetIt.instance;

@InjectableInit(
  // *** This is the name of the function that will be generated by Injectable.
  // It will be used to initialize the GetIt instance.
  initializerName: r'$initGetIt',
  // *** This is to use relative imports for the generated code.
  preferRelativeImports: true,
  // *** with asExtension: false Injectable generates a top-level function that 
  // returns a GetIt instance.
  //
  // Future<GetIt> $initGetIt(GetIt getIt, {String? environment}) async {
  //   return getIt;
  // }
  //
  // You call it like this in injection.dart
  // await $initGetIt(getIt, environment: _getEnvironment(appConfig.flavor));

  // *** with asExtension: true (default) Injectable generates an extension
  // on GetIt instead:
  //
  // extension GetItInjectableX on GetIt {
  //   Future<GetIt> init({String? environment}) async {
  //     // ...registrations
  //     return this;
  //   }
  // }
  //
  // you would call it like this in injection.dart
  // await getIt.init(environment: _getEnvironment(appConfig.flavor));
  asExtension: false,
  
  // *** tells injectable's code generator to skip the "is this type registered?" 
  // check for AppConfig when it build injection.config.dart.
  ignoreUnregisteredTypes: [AppConfig],
)

Future<void> configureInjection(AppConfig appConfig) async {

  // 1. MANUALLY register AppConfig as a singleton
  // This happens BEFORE code generation runs
  getIt.registerSingleton<AppConfig>(appConfig);
  
  // 2. Run code generation to register all @injectable classes
  // These classes can now depend on AppConfig because it's already registered
  await $initGetIt(
    getIt,
    //environment: _getEnvironment(appConfig.flavor),
  );

   // 3. Verify registration (optional)
  assert(getIt.isRegistered<AppConfig>());
}

// String _getEnvironment(Flavor flavor) {
//   switch (flavor) {
//     case Flavor.development:
//       return Environment.dev;
//     case Flavor.staging:
//       return Environment.;
//     case Flavor.production:
//       return Environment.prod;
//   }
// }

