import 'dart:ui';

import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart';
// Import different firebase options based on flavor
// These files are generated by `flutterfire configure`
import 'package:flutter_enterprise_boilerplate/firebase_options_dev.dart' as dev;
import 'package:flutter_enterprise_boilerplate/firebase_options_staging.dart' as staging;
import 'package:flutter_enterprise_boilerplate/firebase_options_prod.dart' as prod;

// # Configure Firebase for development
// flutterfire configure --project=myapp-dev --out=lib/firebase_options_dev.dart

// # Configure Firebase for staging
// flutterfire configure --project=myapp-staging --out=lib/firebase_options_staging.dart

// # Configure Firebase for production
// flutterfire configure --project=myapp-prod --out=lib/firebase_options_prod.dart

enum Flavor { dev, staging, prod }

/// Constructed in composition root ([AppInitializer]) and registered manually
/// in [configureInjection]; not constructed by injectable codegen.
class AppConfig extends Equatable {
  final Flavor flavor;
  final String appName;
  final String appSuffix;
  final String appVersion;
  final int appBuildNumber;
  final String apiBaseUrl;
  final Locale defaultLocale;
  
final int apiReceiveTimeout;
final int apiConnectTimeout;
final int apiSendTimeout;

final Duration cacheStalePeriod;
final int cacheMaxSize;
final int cacheMaxObjects;
final Duration cacheCleanupInterval;

  final bool enableLogging;
  final bool enableAnalytics;
  final bool enableCrashlytics;
  final String sentryDsn;
  //final String firebaseOptionsFile;
  final FirebaseOptions firebaseOptions; // Now required, not nullable


  const AppConfig({
    required this.flavor,
    required this.appName,
    required this.appSuffix,
    required this.appVersion,
    required this.appBuildNumber,
    required this.apiBaseUrl,
    required this.defaultLocale,
    required this.apiReceiveTimeout,
    required this.apiConnectTimeout,
    required this.apiSendTimeout,
    required this.enableLogging,
    required this.enableAnalytics,
    required this.enableCrashlytics,
    required this.sentryDsn,
    required this.firebaseOptions,
    // required this.firebaseOptionsFile,
    //   final FirebaseOptions? firebaseOptions;

    required this.cacheStalePeriod,
    required this.cacheMaxSize,
    required this.cacheMaxObjects,
    required this.cacheCleanupInterval,
  });

  factory AppConfig.fromEnv(Flavor flavor) {
    return AppConfig(
      flavor: flavor,
      appName: dotenv.env['APP_NAME'] ?? 'MyApp',
      appSuffix: dotenv.env['APP_SUFFIX'] ?? '',
      appVersion: dotenv.env['APP_VERSION'] ?? '1.0.0',
      appBuildNumber: int.tryParse(dotenv.env['APP_BUILD_NUMBER'] ?? '1') ?? 1,
      apiBaseUrl: dotenv.env['API_BASE_URL'] ?? '',
      defaultLocale: Locale(dotenv.env['DEFAULT_LOCALE'] ?? 'en', dotenv.env['DEFAULT_COUNTRY'] ?? 'US'),
      apiReceiveTimeout: int.tryParse(dotenv.env['API_RECEIVE_TIMEOUT'] ?? '30000') ?? 30000,
      apiConnectTimeout: int.tryParse(dotenv.env['API_CONNECT_TIMEOUT'] ?? '30000') ?? 30000,
      apiSendTimeout: int.tryParse(dotenv.env['API_SEND_TIMEOUT'] ?? '30000') ?? 30000,
      enableLogging: dotenv.env['ENABLE_LOGGING']?.toLowerCase() == 'true',
      enableAnalytics: dotenv.env['ENABLE_ANALYTICS']?.toLowerCase() == 'true',
      enableCrashlytics: dotenv.env['ENABLE_CRASHLYTICS']?.toLowerCase() == 'true',
      sentryDsn: dotenv.env['SENTRY_DSN'] ?? '',
      firebaseOptions: _getFirebaseOptions(flavor), // Direct based on flavor
      //static const Duration _defaultStalePeriod = Duration(days: 7);
      // static const int _defaultMaxSize = 100 * 1024 * 1024; // 100MB
      // static const int _defaultMaxObjects = 1000;
      // static const Duration _defaultCleanupInterval = Duration(hours: 24);
      cacheStalePeriod: Duration(days: int.tryParse(dotenv.env['CACHE_STALE_PERIOD'] ?? '7') ?? 7),
      cacheMaxSize: int.tryParse(dotenv.env['CACHE_MAX_SIZE'] ?? '104857600') ?? 100 * 1024 * 1024, // 100MB
      cacheMaxObjects: int.tryParse(dotenv.env['CACHE_MAX_OBJECTS'] ?? '1000') ?? 1000,
      cacheCleanupInterval: Duration(hours: int.tryParse(dotenv.env['CACHE_CLEANUP_INTERVAL'] ?? '24') ?? 24),
    );
  }
  
   /// Get Firebase options based on flavor
  static FirebaseOptions _getFirebaseOptions(Flavor flavor) {
    switch (flavor) {
      case Flavor.dev:
        return dev.DefaultFirebaseOptions.currentPlatform;
      case Flavor.staging:
        return staging.DefaultFirebaseOptions.currentPlatform;
      case Flavor.prod:
        return prod.DefaultFirebaseOptions.currentPlatform;
    }
  }

  bool get isDev => flavor == Flavor.dev;
  bool get isStaging => flavor == Flavor.staging;
  bool get isProd => flavor == Flavor.prod;

  String get fullAppName => '$appName$appSuffix';

  bool get isSentryEnabled => sentryDsn != null && sentryDsn.isNotEmpty;
    

  @override
  List<Object?> get props => [
        flavor,
        appName,
        appSuffix,
        appVersion,
        appBuildNumber,
        apiBaseUrl,
        apiReceiveTimeout,
        apiConnectTimeout,
        apiSendTimeout,
        enableLogging,
        enableAnalytics,
        enableCrashlytics,
        sentryDsn,
      ];
}


// /// Simplified FirebaseOptions for type safety
// class FirebaseOptions {
//   final String apiKey;
//   final String appId;
//   final String messagingSenderId;
//   final String projectId;
//   final String? authDomain;
//   final String? storageBucket;

//   const FirebaseOptions({
//     required this.apiKey,
//     required this.appId,
//     required this.messagingSenderId,
//     required this.projectId,
//     this.authDomain,
//     this.storageBucket,
//   });
// }